### ISSUE TITLE
Line Graph Component of General Web Page

### ISSUE THREAD

**Issue by KevinFrazier** [plependu/RCHI#26]
2019 PIT Dashboard: https://sites.google.com/ucr.edu/paea-lependu/rchi/pit-2019?authuser=0

In 2019 Riverside County Point-In-Time Homeless Count, create a component showing the "Homeless Population Trend" Line Graph

If you cannot create the filled-in zones (pink and grey), then do not worry and try your best.

With this example, we can use it to modularize it for all other graphs.

**Comment by cameronmorin** [comment]
@igonz044 @KevinFrazier  please review :smile: 

**Pull request:** https://github.com/plependu/RCHI/pull/28
